version: 2
jobs:
  build:
    docker:
      - image: qawolf/qawolf:v0.9.3-alpha.0
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          command: |
            npx qawolf test --all-browsers
          environment:
            QAW_ARTIFACT_PATH: /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts
