version: 2
jobs:
  build:
    docker:
      - image: qawolf/qawolf:v0.7.0
        environment:
          # output artifacts
          QAW_DOM_PATH: /tmp/artifacts
          QAW_LOG_PATH: /tmp/artifacts
          QAW_VIDEO_PATH: /tmp/artifacts
          # parameterize tests
          QAW_DATA_ATTRIBUTE: data-testid
    steps:
      # checkout to include the .qawolf/ folder
      - checkout

      - run:
          command: qawolf test

      - store_artifacts:
          path: /tmp/artifacts
