name: qawolf
on:
  push:
    # test every branch
    # edit below if you only want certain branches tested
    branches: "*"
  schedule:
    # test on schedule using cron syntax
    - cron: "0 * * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - name: qawolf test
        uses: docker://qawolf/qawolf:v0.7.0
        with:
          args: "qawolf test"
        env:
          # output artifacts
          QAW_DOM_PATH: /github/workspace/artifacts
          QAW_LOG_PATH: /github/workspace/artifacts
          QAW_VIDEO_PATH: /github/workspace/artifacts
          # parameterize tests
          QAW_DATA_ATTRIBUTE: data-testid
          QAW_NAVIGATION_TIMEOUT_MS: 120000
      - name: Upload Artifacts
        # include test artifacts
        # edit below to only include artifacts in certain scenarios
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: qawolf
          path: "./artifacts"
